[package]
name = "grayblock-backend"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3.2"
pretty_env_logger = "0.4"
grayblock-frontend = { path = "../frontend" }
mogwai = "0.5"
