name: Rust

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as it uses the current rustc version as its cache key
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test --verbose
